### ISSUE TITLE
Missing `Error` properties on `VFileMessage`

### ISSUE THREAD

**Issue by TaraServer** [wooorm/vfile#2]
Hi, for me, this is a nightmare to debug this issue (I am quite new to JavaScript). The only thing I can tell for sure is that `mdast-lint` works OK if the installed version of `vfile` is 1.1.0 but if I upgrade it to 1.1.1, it starts failing. I guess it has something to do with the recent changes in the message object. `vfile-reporter` expects a `stack` property which is not defined.

Here is an example failure:
```
<snip>

- foo

TypeError: Cannot read property 'slice' of undefined
    at /Users/ServerTara/Radek/Becki/node_modules/vfile-reporter/index.js:215:30
    at Array.map (native)
    at /Users/ServerTara/Radek/Becki/node_modules/vfile-reporter/index.js:183:29
    at Array.forEach (native)
    at reporter (/Users/ServerTara/Radek/Becki/node_modules/vfile-reporter/index.js:167:11)
    at Ware.log (/Users/ServerTara/Radek/Becki/node_modules/mdast/lib/cli/file-set-pipeline/log.js:30:23)
    at Ware.<anonymous> (/Users/ServerTara/Radek/Becki/node_modules/wrap-fn/index.js:75:16)
    at Ware.<anonymous> (/Users/ServerTara/Radek/Becki/node_modules/wrap-fn/index.js:57:27)
    at FileSet.next (/Users/ServerTara/Radek/Becki/node_modules/ware/lib/index.js:85:20)
    at FileSet.done (/Users/ServerTara/Radek/Becki/node_modules/wrap-fn/index.js:121:18)
```
To reproduce it, you need to run `mdast-lint` on a Markdown file which contains a mistake.

**Comment by wooorm** [comment]
Thanks for letting me know!
